import Providers from "@utils/Providers";
import "@styles/globals.css";
import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../public/font/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className="font-pretendard font-medium">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
